# Generated by Django 5.1 on 2024-09-09 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historias_clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='hc_laboratorio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConsultaControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('cc_laboratorio', models.TextField(blank=True, null=True)),
                ('estado_actual', models.TextField()),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='historias_clinicas.historiaclinica')),
            ],
        ),
        migrations.DeleteModel(
            name='RevisionHistoria',
        ),
    ]
